apiVersion: v2
appVersion: latest
name: bee
version: 0.10.14
kubeVersion: ">=1.15.0-0"
description: Ethereum Swarm Bee Helm chart for Kubernetes
home: https://www.ethswarm.org
icon: https://docs.ethswarm.org/img/swarm-logo-2.svg
keywords:
  - blockchain
  - ethereum
  - storage
  - swarm
  - web3
maintainers:
  - name: devops
    email: devops@ethswarm.org
  - name: svetomir
    email: svetomir@ethswarm.org
  - name: vandot
    email: vandot@ethswarm.org
sources:
  - https://github.com/ethersphere/bee
type: application
