apiVersion: v2
appVersion: latest
name: bee
version: 0.2.4
description: Ethereum Swarm Bee Helm chart for Kubernetes
home: https://swarm.ethereum.org
icon: https://swarm-guide.readthedocs.io/en/latest/_images/swarm.png
keywords:
  - blockchain
  - ethereum
  - storage
  - swarm
  - web3
maintainers:
  - name: svetomir
    email: svetomir@ethereum.org
sources:
  - https://github.com/ethersphere/bee
type: application
