{{- if and .Values.check.pullsync.enabled (not .Values.singleJob.enabled) -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "beekeeper.fullname" . }}-pullsync
  labels:
    {{- include "beekeeper.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.check.pullsync.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.check.pullsync.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.check.pullsync.failedJobsHistoryLimit }}
  concurrencyPolicy: "{{ .Values.check.pullsync.concurrencyPolicy }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "beekeeper.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          serviceAccountName: {{ include "beekeeper.serviceAccountName" . }}
          {{- if .Values.initPing.enabled }}
          initContainers:
            - name: init-ping
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: BEEKEEPER_API_DOMAIN
                  value: "{{ .Values.beeCluster.apiDomain }}"
                - name: BEEKEEPER_API_HOSTNAMES
                  value: "{{ .Values.beeCluster.apiHostnames }}"
                - name: BEEKEEPER_API_INSECURE_TLS
                  value: "{{ .Values.beeCluster.apiInsecureTLS }}"
                - name: BEEKEEPER_API_SCHEME
                  value: "{{ .Values.beeCluster.apiScheme }}"
                - name: BEEKEEPER_DEBUG_API_DOMAIN
                  value: "{{ .Values.beeCluster.debugApiDomain }}"
                - name: BEEKEEPER_DEBUG_API_HOSTNAMES
                  value: "{{ .Values.beeCluster.debugApiHostnames }}"
                - name: BEEKEEPER_DEBUG_API_INSECURE_TLS
                  value: "{{ .Values.beeCluster.debugApiInsecureTLS }}"
                - name: BEEKEEPER_DEBUG_API_SCHEME
                  value: "{{ .Values.beeCluster.debugApiScheme }}"
                - name: BEEKEEPER_DISABLE_NAMESPACE
                  value: "{{ .Values.beeCluster.disableNamespace }}"
                - name: BEEKEEPER_INSECURE_TLS
                  value: "{{ .Values.beeCluster.insecureTLS }}"
                - name: BEEKEEPER_NAMESPACE
                  value: "{{ .Values.beeCluster.namespace }}"
                - name: BEEKEEPER_NODE_COUNT
                  value: "{{ .Values.beeCluster.nodeCount }}"
              command:
                - sh
                - -c
                - >
                  until beekeeper check pingpong; do echo "waiting for the cluster..."; sleep 1; done
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: BEEKEEPER_API_DOMAIN
                  value: "{{ .Values.beeCluster.apiDomain }}"
                - name: BEEKEEPER_API_HOSTNAMES
                  value: "{{ .Values.beeCluster.apiHostnames }}"
                - name: BEEKEEPER_API_INSECURE_TLS
                  value: "{{ .Values.beeCluster.apiInsecureTLS }}"
                - name: BEEKEEPER_API_SCHEME
                  value: "{{ .Values.beeCluster.apiScheme }}"
                - name: BEEKEEPER_DEBUG_API_DOMAIN
                  value: "{{ .Values.beeCluster.debugApiDomain }}"
                - name: BEEKEEPER_DEBUG_API_HOSTNAMES
                  value: "{{ .Values.beeCluster.debugApiHostnames }}"
                - name: BEEKEEPER_DEBUG_API_INSECURE_TLS
                  value: "{{ .Values.beeCluster.debugApiInsecureTLS }}"
                - name: BEEKEEPER_DEBUG_API_SCHEME
                  value: "{{ .Values.beeCluster.debugApiScheme }}"
                - name: BEEKEEPER_DISABLE_NAMESPACE
                  value: "{{ .Values.beeCluster.disableNamespace }}"
                - name: BEEKEEPER_INSECURE_TLS
                  value: "{{ .Values.beeCluster.insecureTLS }}"
                - name: BEEKEEPER_NAMESPACE
                  value: "{{ .Values.beeCluster.namespace }}"
                - name: BEEKEEPER_NODE_COUNT
                  value: "{{ .Values.beeCluster.nodeCount }}"
                - name: BEEKEEPER_PUSH_GATEWAY
                  value: "{{ .Values.beeCluster.pushGateway }}"
                - name: BEEKEEPER_PUSH_METRICS
                  value: "{{ .Values.beeCluster.pushMetrics }}"
              args:
                - check
                - pullsync
                - --chunks-per-node
                - "{{ .Values.check.pullsync.chunksPerNode }}"
                - --upload-node-count
                - "{{ .Values.check.pullsync.uploadNodeCount }}"
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}

{{- end -}}
