{{- if and .Values.singleJob.enabled -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "beekeeper.fullname" . }}
  labels:
    {{- include "beekeeper.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "beekeeper.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "beekeeper.serviceAccountName" . }}
      {{- if .Values.initPing.enabled }}
      initContainers:
        - name: init-ping
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BEEKEEPER_API_DOMAIN
              value: "{{ .Values.beeCluster.apiDomain }}"
            - name: BEEKEEPER_API_HOSTNAMES
              value: "{{ .Values.beeCluster.apiHostnames }}"
            - name: BEEKEEPER_API_INSECURE_TLS
              value: "{{ .Values.beeCluster.apiInsecureTLS }}"
            - name: BEEKEEPER_API_SCHEME
              value: "{{ .Values.beeCluster.apiScheme }}"
            - name: BEEKEEPER_DEBUG_API_DOMAIN
              value: "{{ .Values.beeCluster.debugApiDomain }}"
            - name: BEEKEEPER_DEBUG_API_HOSTNAMES
              value: "{{ .Values.beeCluster.debugApiHostnames }}"
            - name: BEEKEEPER_DEBUG_API_INSECURE_TLS
              value: "{{ .Values.beeCluster.debugApiInsecureTLS }}"
            - name: BEEKEEPER_DEBUG_API_SCHEME
              value: "{{ .Values.beeCluster.debugApiScheme }}"
            - name: BEEKEEPER_DISABLE_NAMESPACE
              value: "{{ .Values.beeCluster.disableNamespace }}"
            - name: BEEKEEPER_INSECURE_TLS
              value: "{{ .Values.beeCluster.insecureTLS }}"
            - name: BEEKEEPER_NAMESPACE
              value: "{{ .Values.beeCluster.namespace }}"
            - name: BEEKEEPER_NODE_COUNT
              value: "{{ .Values.beeCluster.nodeCount }}"
          command:
            - sh
            - -c
            - >
              until beekeeper check pingpong; do echo "waiting for the cluster..."; sleep 1; done
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BEEKEEPER_API_DOMAIN
              value: "{{ .Values.beeCluster.apiDomain }}"
            - name: BEEKEEPER_API_HOSTNAMES
              value: "{{ .Values.beeCluster.apiHostnames }}"
            - name: BEEKEEPER_API_INSECURE_TLS
              value: "{{ .Values.beeCluster.apiInsecureTLS }}"
            - name: BEEKEEPER_API_SCHEME
              value: "{{ .Values.beeCluster.apiScheme }}"
            - name: BEEKEEPER_DEBUG_API_DOMAIN
              value: "{{ .Values.beeCluster.debugApiDomain }}"
            - name: BEEKEEPER_DEBUG_API_HOSTNAMES
              value: "{{ .Values.beeCluster.debugApiHostnames }}"
            - name: BEEKEEPER_DEBUG_API_INSECURE_TLS
              value: "{{ .Values.beeCluster.debugApiInsecureTLS }}"
            - name: BEEKEEPER_DEBUG_API_SCHEME
              value: "{{ .Values.beeCluster.debugApiScheme }}"
            - name: BEEKEEPER_DISABLE_NAMESPACE
              value: "{{ .Values.beeCluster.disableNamespace }}"
            - name: BEEKEEPER_INSECURE_TLS
              value: "{{ .Values.beeCluster.insecureTLS }}"
            - name: BEEKEEPER_NAMESPACE
              value: "{{ .Values.beeCluster.namespace }}"
            - name: BEEKEEPER_NODE_COUNT
              value: "{{ .Values.beeCluster.nodeCount }}"
            - name: BEEKEEPER_PUSH_GATEWAY
              value: "{{ .Values.beeCluster.pushGateway }}"
            - name: BEEKEEPER_PUSH_METRICS
              value: "{{ .Values.beeCluster.pushMetrics }}"
            - name: BEEKEEPER_UPLOAD_NODE_COUNT
              value: "{{ .Values.singleJob.uploadNodeCount }}"
            - name: BEEKEEPER_CHUNKS_PER_NODE
              value: "{{ .Values.singleJob.chunksPerNode }}"
            - name: PINGPONG_ENABLED
              value: "{{ .Values.check.pingpong.enabled }}"
            - name: BALANCES_ENABLED
              value: "{{ .Values.check.balances.enabled }}"
            - name: SETTLEMENTS_ENABLED
              value: "{{ .Values.check.settlements.enabled }}"
            - name: PUSHSYNC_ENABLED
              value: "{{ .Values.check.pushsync.enabled }}"
            - name: RETRIEVAL_ENABLED
              value: "{{ .Values.check.retrieval.enabled }}"
            - name: PULLSYNC_ENABLED
              value: "{{ .Values.check.pullsync.enabled }}"
            - name: CHUNKREPAIR_ENABLED
              value: "{{ .Values.check.chunkrepair.enabled }}"
            - name: MANIFEST_ENABLED
              value: "{{ .Values.check.manifest.enabled }}"
          command:
            - sh
            - -c
            - >
              if [ "${PINGPONG_ENABLED}" = "true" ]; then beekeeper check pingpong || exit 1; fi;
              if [ "${BALANCES_ENABLED}" = "true" ]; then beekeeper check balances || exit 1; fi;
              if [ "${SETTLEMENTS_ENABLED}" = "true" ]; then beekeeper check settlements || exit 1; fi;
              if [ "${PUSHSYNC_ENABLED}" = "true" ]; then beekeeper check pushsync || exit 1 && beekeeper check pushsync --upload-chunks || exit 1; fi;
              if [ "${RETRIEVAL_ENABLED}" = "true" ]; then beekeeper check retrieval || exit 1; fi;
              if [ "${PULLSYNC_ENABLED}" = "true" ]; then beekeeper check pullsync || exit 1; fi;
              if [ "${CHUNKREPAIR_ENABLED}" = "true" ]; then beekeeper check chunkrepair || exit 1; fi;
              if [ "${MANIFEST_ENABLED}" = "true" ]; then beekeeper check manifest || exit 1; fi;
      restartPolicy: "{{ .Values.singleJob.restartPolicy }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}

{{- end -}}
