apiVersion: v1
kind: Service
metadata:
  name: geth-swap
  labels:
    {{- include "geth-swap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.wsport }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "geth-swap.selectorLabels" . | nindent 4 }}
