{{/* OneChart ingress snippet */}}
{{- define "onechart.ingress" }}
{{- $robustName := include "robustName" .root.Release.Name -}}
{{- $resourceName := $robustName -}}
{{- if .longName }}
{{- $resourceName = printf "%s-%s" $robustName (include "robustName" .ingress.host) -}}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:  
  name: {{ $resourceName }}
  namespace: {{ .root.Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" .root | nindent 4 }}
  {{- if or (or .root.Values.gitSha .ingress.annotations) .root.Values.gitRepository }}
  annotations:
    {{- if .ingress.annotations }}
      {{- toYaml .ingress.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .ingress.ingressClassName }}
  ingressClassName: {{ .ingress.ingressClassName }}
  {{- end }}
  {{- if default false .ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .ingress.host | quote }}
      secretName: {{ printf "tls-%s" $resourceName }}
  {{- end }}
  rules:
    - host: {{ .ingress.host | quote }}
      http:
        paths:
          {{- if .ingress.paths }}
            {{- range .ingress.paths }}
            - path: {{ .path | default "/" | quote }}
              pathType: {{ .pathType | default "ImplementationSpecific" | quote }}
              backend:
                service:
                  name: {{ .service | default $robustName }}
                  port:
                    number: {{ .port | default $.root.Values.service.port }}
            {{- end }}
          {{- else }}
            - path: {{ .ingress.path | default "/" | quote }}
              pathType: "ImplementationSpecific"
              backend:
                service:
                  name: {{ $robustName }}
                  port:
                    number: {{ .root.Values.service.port }}
          {{- end }}
{{- end }}

{{- with .Values.ingress }}
  {{- if ne .enabled false }}
  {{- template "onechart.ingress" (dict "root" $ "ingress" .) }}
  {{- end }}
{{- end }}

{{- range .Values.ingresses }}
  {{- template "onechart.ingress" (dict "root" $ "ingress" . "longName" true) }}
{{- end }}
