apiVersion: v2
appVersion: latest
name: beekeeper
version: 0.4.7
description: Ethereum Swarm Beekeeper Helm chart for Kubernetes
home: https://www.ethswarm.org
icon: https://docs.ethswarm.org/img/swarm-logo-2.svg
keywords:
  - blockchain
  - ethereum
  - storage
  - swarm
  - web3
maintainers:
  - name: svetomir
    email: svetomir@ethswarm.org
sources:
  - https://github.com/ethersphere/beekeeper
type: application
