apiVersion: v2
appVersion: 0.1.0
name: eks-local-disk-provisioner
version: 0.1.2
description: AWS eks-local-disk-provisioner Helm chart for Kubernetes
home: https://www.ethswarm.org
icon: https://docs.ethswarm.org/img/swarm-logo-2.svg
keywords:
  - aws
  - kubernetes
  - eks
  - local disk provisioner
  - local persistent volume
  - sig-storage-local-static-provisioner
maintainers:
  - name: svetomir
    email: svetomir@ethereum.org
sources:
  - https://github.com/ethersphere/eks-local-disk-provisioner
type: application
