apiVersion: v2
dependencies:
- name: common
  repository: file://charts/common
  version: 0.7.0
description: Chart to build and deploy beeport-ui
name: beeport-ui
type: application
version: 0.75.0
home: https://www.ethswarm.org
icon: https://docs.ethswarm.org/img/swarm-logo-2.svg
keywords:
  - blockchain
  - swarm
maintainers:
  - name: darkobas
    email: darkobas@ethswarm.org
sources:
  - https://github.com/ethersphere/beeport
