# Default values for tokenexporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: darkobas/tokenexporter
  tag: latest
  pullPolicy: IfNotPresent

tokenexporter:
  gethEndpoint: http://rpc-gnosis-haproxy.default.svc.godfather2.local
  interval: 60

addressesTxt:
  enabled: true
  existingConfigMap: "balance-addresses"  # Name of the existing ConfigMap
  # addresses: |
  #   bittrex:0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98
  #   etherdelta:0x8d12A197cB00D4747a1fe03395095ce2A5CC6819

tokensJson:
  enabled: true
  tokens: |
    [
      {
        "address": "0xdbf3ea6f5bee45c02255b2c26a16f300502f68da",
        "symbol": "BZZ",
        "decimal": 16,
        "type": "default"
      }
    ]

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

serviceMonitor:
  enabled: true
  additionalLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9021

ingress:
  enabled: false
  annotations: {}
    # nginx.org/client-max-body-size: "0"
    # nginx.org/proxy-connect-timeout: "60s"
    # nginx.org/proxy-read-timeout: "60s"
  class: "nginx"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
